# Generated by Django 4.2.8 on 2024-01-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0014_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="attractions.region",
            ),
        ),
        migrations.AlterField(
            model_name="regioncity",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="region_cities",
                to="attractions.region",
            ),
        ),
    ]
