# Generated by Django 4.2.8 on 2024-01-22 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attractions", "0015_city_region_alter_regioncity_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupKind",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "db_table": "attraction_group_kind",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("name", models.CharField(db_index=True, max_length=32, unique=True)),
                ("icon", models.FileField(blank=True, null=True, upload_to="")),
                ("position", models.PositiveIntegerField(null=True)),
                ("kind", models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="groups",
                    to="attractions.groupkind",
                )),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "db_table": "attraction_groups",
            },
        ),
        migrations.CreateModel(
            name="SubGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("name", models.CharField(db_index=True, max_length=32, unique=True)),
                ("icon", models.FileField(blank=True, null=True, upload_to="")),
                ("position", models.PositiveIntegerField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="attractions.group",
                    ),
                ),
            ],
            options={
                "db_table": "attraction_subgroups",
            },
        ),
        migrations.AddField(
            model_name="attraction",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attractions",
                to="attractions.group",
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attractions",
                to="attractions.subgroup",
            ),
        ),
        migrations.AddField(
            model_name="attractionhistory",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="attractions.group",
            ),
        ),
        migrations.AddField(
            model_name="attractionhistory",
            name="subgroup",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="attractions.subgroup",
            ),
        ),
    ]
