# Generated by Django 4.2.8 on 2024-01-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0016_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["kind", "position"]},
        ),
        migrations.AlterModelOptions(
            name="subgroup",
            options={"ordering": ["group", "position"]},
        ),
    ]
