# Generated by Django 4.2.8 on 2024-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0018_transfer_stops"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_user_can_contribute",
            field=models.BooleanField(default=False),
        ),
    ]
