# Generated by Django 4.2.8 on 2024-02-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0019_can_contribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="layout",
            field=models.CharField(
                choices=[("list", "List"), ("banner", "Banner"), ("name", "Name")],
                default="list",
                max_length=6,
                verbose_name="Layout",
            ),
        ),
    ]
