# Generated by Django 4.2.10 on 2024-09-06 16:04

from django.db import migrations, models

def set_groups_set(apps, schema_editor):
    Attraction = apps.get_model("attractions", "Attraction")
    for attraction in Attraction.objects.all():
        if attraction.group is not None:
            attraction.groups.set([attraction.group])
        if attraction.subgroup is not None:
            attraction.subgroups.set([attraction.subgroup])


def set_group(apps, schema_editor):
    Attraction = apps.get_model("attractions", "Attraction")
    attractions = Attraction.objects.all()
    for attraction in attractions:
        attraction.group = attraction.groups.first()
        attraction.subgroup = attraction.subgroups.first()
    
    Attraction.objects.bulk_update(attractions, ["group", "subgroup"])


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0020_group_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="groups",
            field=models.ManyToManyField(
                related_name="attractions", to="attractions.group"
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="subgroups",
            field=models.ManyToManyField(
                blank=True, related_name="attractions", to="attractions.subgroup"
            ),
        ),
        migrations.RunPython(set_groups_set, set_group),
        migrations.RemoveField(
            model_name="attraction",
            name="group",
        ),
        migrations.RemoveField(
            model_name="attraction",
            name="subgroup",
        ),
        migrations.RemoveField(
            model_name="attractionhistory",
            name="group",
        ),
        migrations.RemoveField(
            model_name="attractionhistory",
            name="subgroup",
        ),
    ]
