# Generated by Django 4.2.10 on 2024-12-26 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attractions", "0021_many_groups_subgroups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGalleryPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("file", models.FileField(upload_to="")),
                ("description", models.CharField(max_length=255, null=True, blank=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_gallery_photos",
                        to="attractions.region",
                    ),
                ),
            ],
            options={
                "db_table": "contents_user_gallery_photos",
                "ordering": ("-created_dttm",),
            },
        ),
    ]
