CELERY_BROKER_URL = "redis://0.0.0.0:6379"
CELERY_RESULT_BACKEND = "redis://0.0.0.0:6379"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Moscow"
