# Generated by Django 4.1.5 on 2023-03-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_auto"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payer",
            field=models.JSONField(blank=True, null=True, verbose_name="Payer"),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payer",
            field=models.JSONField(blank=True, null=True, verbose_name="Payer"),
        ),
    ]
