# Generated by Django 4.1.5 on 2023-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_auto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Card Holder Name"
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Card Holder Name"
            ),
        ),
    ]
