export const colors = {
  light: {
    primary: {
      main: '#296587',
      dark: '#000B77',
      update1: '#296587',
    },
    secondary: '',
    error: '#FF4B5C',
    warning: '#FF4B5C',
    info: '',
    success: '',
    text: {
      primary: '#0F1B2E',
      link: '#1A74E8',
      linkActive: '#296587',
      contrast: '#FFFFFF',
      dimmed: '#808695',
      outlinedButton: '#0F1B2E',
      circularProgress: '#5D8ABC',
      profileButtonHovered: '#66BFBF',
      removeProfileButton: '#FF4B5C',
    },
    icon: {
      menu: '#5D8ABC',
    },
    background: {
      root: '#FFFFFF',
      footer: '#F4F4F4',
      card: '#F6FAFF',
      cardSecondary: '#66BFBF',
      disabled: '#D9D9D9',
      navigationButton: '#FFE26E',
      feedbackForm: '#FFE16E',
      input: '#FFFFFF',
      button: '#1299C1',
      searchInput: '#F6FAFF',
      swiperPagination: '#FFFFFF',
      swiperPaginationActive: '#000B77',
      ratingStar: '#FFD841',
      routePointPosition: '#5D8ABC',
      skeleton: '#F6FAFF',
      searchResultHovered: '#F6FAFF',
      avatar: '#FFFFFF',
      warnRed: '#FF4B5C',
    },
    border: {
      divider: '#80869580',
      outlinedButton: '#0F1B2E',
      outlinedInput: '#7A7B81',
      outlinedInputFocused: '#66BFBF',
      tile: '#C0C0C0',
      select: '#0F1B2E',
    },
  },
  dark: {
    primary: {
      main: '#296587',
      dark: '#000B77',
      update1: '#296587',
    },
    secondary: '',
    error: '#FF4B5C',
    warning: '#FF4B5C',
    info: '',
    success: '',
    text: {
      primary: '#0F1B2E',
      link: '#1A74E8',
      linkActive: '#296587',
      contrast: '#FFFFFF',
      dimmed: '#808695',
      outlinedButton: '#000B77',
      circularProgress: '#5D8ABC',
      profileButtonHovered: '#66BFBF',
      removeProfileButton: '#FF4B5C',
    },
    icon: {
      menu: '#5D8ABC',
    },
    background: {
      root: '#FFFFFF',
      footer: '#F4F4F4',
      card: '#F6FAFF',
      cardSecondary: '#66BFBF',
      disabled: '#D9D9D9',
      navigationButton: '#FFE26E',
      feedbackForm: '#FFE16E',
      input: '#FFFFFF',
      button: '#66BFBF',
      searchInput: '#F6FAFF',
      swiperPagination: '#FFFFFF',
      swiperPaginationActive: '#000B77',
      ratingStar: '#FFD841',
      routePointPosition: '#5D8ABC',
      skeleton: '#F6FAFF',
      searchResultHovered: '#F6FAFF',
      avatar: '#FFFFFF',
      warnRed: '#FF4B5C',
    },
    border: {
      divider: '#80869580',
      outlinedButton: '#0F1B2E',
      outlinedInput: '#7A7B81',
      outlinedInputFocused: '#7A7B81',
      tile: '#C0C0C0',
      select: '#0F1B2E',
    },
  },
}
