# Generated by Django 4.1 on 2022-11-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_auto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
