# Generated by Django 4.2.8 on 2023-12-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_auto"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "request_id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("value", models.CharField(max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("retry_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "verification code",
                "verbose_name_plural": "verification codes",
                "db_table": "verification_codes",
            },
        ),
    ]
