# Generated by Django 4.2.10 on 2024-12-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0006_auto"),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteProperties",
            fields=[
                (
                    "route",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="properties",
                        serialize=False,
                        to="routes.route",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("winter", "зима"),
                            ("spring", "весна"),
                            ("summer", "лето"),
                            ("autumn", "осень"),
                            ("all", "все время года"),
                        ],
                        db_index=True,
                        max_length=6,
                        null=True,
                        verbose_name="Season",
                    ),
                ),
                ("rise_degree", models.IntegerField(blank=True, null=True)),
                ("is_overnight", models.BooleanField(blank=True, null=True)),
                ("is_family", models.BooleanField(blank=True, null=True)),
                ("is_on_horseback", models.BooleanField(blank=True, null=True)),
                ("is_on_foot", models.BooleanField(blank=True, null=True)),
                ("is_on_quad_bike", models.BooleanField(blank=True, null=True)),
                ("is_on_car", models.BooleanField(blank=True, null=True)),
                ("is_swimming", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "route_properties",
            },
        ),
    ]
