# Generated by Django 4.2.10 on 2025-01-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0007_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="custom_properties",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Custom Properties"
            ),
        ),
        migrations.AddField(
            model_name="routehistory",
            name="custom_properties",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Custom Properties"
            ),
        ),
    ]
